In [90]:
#read the data
import pandas as pd
df=pd.read_csv(r"C:\Users\anshika srivastava\Documents\abusedetectiondata.csv" , sep=",")
df=df.dropna()
df.shape


(855, 2)

In [91]:
#requirements
import nltk
import numpy as np
import pandas as pd
import re
import matplotlib.pyplot as plt 
import seaborn as sb
from nltk.corpus import stopwords
import warnings 
warnings.filterwarnings("ignore")
import unidecode

from nltk.stem import WordNetLemmatizer 
nltk.download('wordnet')
from nltk.stem import PorterStemmer
nltk.download('punkt')
from nltk.tokenize import word_tokenize 
import matplotlib.animation as animation
import operator

from collections import Counter

import re , string
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords.words('english')

[nltk_data] Downloading package wordnet to C:\Users\anshika
[nltk_data]     srivastava\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\anshika
[nltk_data]     srivastava\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\anshika
[nltk_data]     srivastava\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [92]:
print(list(df))

['text', 'value']


In [93]:

df.dropna()#to empty nan  rows
df['text'] = df['text'].str.lower()
df.shape


(855, 2)

In [94]:
review=df['text'][0]
print(review)

मोदी  क्या आये दीदी, 
पटेल,बोस, भगत सिंह, राज गुरु, सुखदेव,
सब याद आ गए।

पहले तो नेहरू से बड़ा महान कोई नही था।
   https:// twitter.com/priyankagandhi /status/1189777932379709440   …


In [95]:
for i in range(0 , len(df)):
    review=word_tokenize(df['text'][i])
    print(review)

['मोदी', 'क्या', 'आये', 'दीदी', ',', 'पटेल', ',', 'बोस', ',', 'भगत', 'सिंह', ',', 'राज', 'गुरु', ',', 'सुखदेव', ',', 'सब', 'याद', 'आ', 'गए।', 'पहले', 'तो', 'नेहरू', 'से', 'बड़ा', 'महान', 'कोई', 'नही', 'था।', 'https', ':', '//', 'twitter.com/priyankagandhi', '/status/1189777932379709440', '…']
['है', 'कौन', 'ये', 'मादरचोद']
['आस्था', 'के', 'महापर्व', 'छठी', 'मे', 'जो', 'माँ', 'अपने', 'बच्चों', 'के', 'लिये', 'निर्जला', 'व्रत', 'रखती', 'है', 'वही', 'बच्चा', 'पलायन', 'की', 'मार', 'झेल', 'रहा', 'हो', '।', 'उस', 'माँ', '-बेटे', 'का', 'ये', 'निक्कमी', 'सरकार', 'नही', 'समझ', 'सकती', 'है', '।', '@', 'nitishkumar', '@', 'sushilmodi', '@', 'narendramodi', '@', 'pmoindia']
['वर्ष', '2015', 'में', 'भारत', 'सरकार', 'द्वारा', '31', 'अक्टूबर', 'को', 'प्रतिवर्ष', 'राष्ट्रीय', 'एकता', 'दिवस', 'के', 'रूप', 'में', 'मनाने', 'का', 'निर्णय', 'लिया', 'गया', '।', '31', 'अक्टूबर', 'ही', 'वह', 'दिन', 'है', 'जिस', 'दिन', 'भारत', 'माता', 'को', 'लौह', 'पुरुष', 'सरदार', 'पटेल', 'जैसा', 'हीरा', 'मिला', 'था', '।', 'pi

KeyError: 440

In [96]:
df.shape


(855, 2)

In [97]:
df=df.dropna()

In [98]:
df.shape

(855, 2)

In [99]:
df.shape

(855, 2)

In [100]:
df=df.dropna()
df.shape

(855, 2)

In [101]:
df=df.dropna()
df.shape

(855, 2)

In [102]:
df=df.dropna()
df.head()

text  value
0  मोदी  क्या आये दीदी, \nपटेल,बोस, भगत सिंह, राज...    0.0
1                                 है कौन ये  मादरचोद    1.0
2  आस्था के महापर्व छठी मे जो माँ अपने बच्चों के ...    0.0
3  वर्ष 2015 में भारत  सरकार  द्वारा 31 अक्टूबर क...    0.0
4  केजरीवाल  सरकार जो फ्री टिकट देने का ढिंढोरा प...    0.0

In [103]:
#stopwords list in english
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [104]:
df=df.dropna()

In [105]:
df.shape

(855, 2)

In [106]:
import numpy as np
import pandas as pd
df=pd.read_csv(r"C:\Users\anshika srivastava\Documents\abusedetectiondata.csv" , sep=",")
df=df.dropna()
df.shape

(855, 2)

In [107]:
data=df.text.tolist()
valueto=df.value.tolist()
for i in range(0 ,len(data)):
    data[i] =re.sub('@[\w]+','',data[i])
    data[i] = re.sub(r'^https?:\/\/.*[\r\n]*', '', data[i], flags=re.MULTILINE)
dfres = pd.DataFrame({'text': data, 'value': valueto})
print(data[:20])


    

['मोदी  क्या आये दीदी, \nपटेल,बोस, भगत सिंह, राज गुरु, सुखदेव,\nसब याद आ गए।\n\nपहले तो नेहरू से बड़ा महान कोई नही था।\n   https:// twitter.com/priyankagandhi /status/1189777932379709440 \xa0 …', 'है कौन ये  मादरचोद', 'आस्था के महापर्व छठी मे जो माँ अपने बच्चों के लिये निर्जला व्रत रखती है वही बच्चा पलायन की मार झेल रहा हो । उस माँ -बेटे का ये निक्कमी  सरकार  नही समझ सकती है ।       ', 'वर्ष 2015 में भारत  सरकार  द्वारा 31 अक्टूबर को प्रतिवर्ष राष्ट्रीय एकता दिवस के रूप में मनाने का निर्णय लिया गया । 31 अक्टूबर ही वह दिन है जिस दिन भारत माता को लौह पुरुष सरदार पटेल जैसा हीरा मिला था ।  pic.twitter.com/GCLYgH8Vyg', 'केजरीवाल  सरकार जो फ्री टिकट देने का ढिंढोरा पीट रही है, उसका सच जानिए, जुड़िए लाइव।  https://www. pscp.tv/w/cIrDzTFkclFl a1pvTGt3amJ8MU95S0FlQXpsYnlLYl1uaQywmU1sX1wGUtyuNXFXyZWoD1eqw9u3nByPzFQK \xa0 …', 'कभी आपने अपने घर पर 1500-2500 रुपए में एक दीया जलाया है?\n\nएक दीये की कीमत मुश्किल से 5रु. और बाती तेल मिला कर अधिकतम 10रु. होगी।\n\nमान लो दीया प्रज्वलित करने आपने एक कर्

In [108]:
dfres.head(30)

text  value
0   मोदी  क्या आये दीदी, \nपटेल,बोस, भगत सिंह, राज...    0.0
1                                  है कौन ये  मादरचोद    1.0
2   आस्था के महापर्व छठी मे जो माँ अपने बच्चों के ...    0.0
3   वर्ष 2015 में भारत  सरकार  द्वारा 31 अक्टूबर क...    0.0
4   केजरीवाल  सरकार जो फ्री टिकट देने का ढिंढोरा प...    0.0
5   कभी आपने अपने घर पर 1500-2500 रुपए में एक दीया...    0.0
6   बीजेपी को शिवसेना की  गांड  पर लात मारने चाहिए...    1.0
7   10 साल आपने भी इसी उत्तर प्रदेश की जनता का विश...    0.0
8       क्यों की  गांड़  में डंडा डालने वाले कमजोर है    1.0
9   बोलो टोटी चोर क्या मिला pic.twitter.com/0MjqfN...    0.0
10  दिल्ली के पूर्वांचल, बिहार, मिथिला, मैथिली, भो...    0.0
11               रंडी  पोर्न स्टार की औलाद प्रकाश राज    1.0
12  मोदी  ने राजौरी में जवानों के साथ मनाई दिवाली ...    0.0
13  # Bhikhari  ये    बहुत ही शातिर है  बहनचोद  दे...    1.0
14  जनसंख्या बढ़ाओ देश कब्जाओ..\nएक बच्चा पैदा कर ...    0.0
15  जो चीज टूटी है वो लिबरल की  गांड़  है बीबी\nदु...    1.0
16  @ KapilMishra_IND  आपने देश और  केजरीवाल  मे स...    0.0
17  तकरीबन एक साल बाद रात के 2 बजे उसका फ़ोन आया \...    1.0
18  राजनीतिक छक्कों और रुदालियों की परम आवश्यकता ह...    1.0
19  इनके सावरकर आंग्रेजों के सामने झुक कर मरवा लिए...    1.0
20  इस तर्क के हिसाब से  बहनचोद  का खिताब अकबर ओर ...    1.0
21  बचपन में भी  मादरचोद  थे अब महामादरचोद हो गये ...    1.0
22  राजस्थान  सरकार  का एक ही उद्देश्य का साथ सबका...    0.0
23  ये झोपड़ी का खरामी ह   भडवा पोर्न का ही पैदायि...    1.0
24  भाई वो गद्दार इसके घर सर्जीकल इस्ट्राइक कर गया...    1.0
25  इसमें विवादित क्या है बे  मादरचोद  देखा नही कम...    1.0
26  # भोसड़ी  के #कालू  तू क्यू नहीं चला जाता तेरे...    1.0
27  सहज सरल मृदुभाषी सक्रिय जननेता म.प्र  सरकार  म...    0.0
28  मोदी  जी बोले थे, नोट बन्दी से आतंकवाद समाप्त ...    0.0
29  ये भड़वे वही है जो किसी शांतिदूत की पिटाई हो ज...    1.0

In [109]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\anshika
[nltk_data]     srivastava\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [110]:

stp=list(open(r"C:\Users\anshika srivastava\Desktop\abusestopword.txt"  ,'r' , encoding='utf-8'))#self made list of stopwords
stop=set(stopwords.words('english'))

for i in range(0 , len(stp)):
    stp[i]=re.sub('\n', '',stp[i])

corpus = []
 
data=df.text.tolist()
valueto=df.value.tolist()

#preprocessing the data
for i in range(0 ,len(data)):
    data[i] =re.sub('@[\w]+','',data[i])
    data[i] = re.sub(r'\/\/.*[\r\n]*', '', data[i], flags=re.MULTILINE)
    data[i] = re.sub('pic.*[\r\n]*', '', data[i])
    data[i] = re.sub('#', '' , data[i])
    data[i] = re.sub('\d+', '' , data[i]) 
    data[i] = re.sub('http:', '' , data[i])
    data[i] = re.sub('https:' , '' , data[i])
   
    data[i] = data[i].translate(data[i].maketrans('', '', '"'))
    data[i] = data[i].translate(data[i].maketrans('', '', string.punctuation))
for j in range(300 , len(data)):
    data[j]=data[j].lower()
    
#implementing stopwords
for i in range(0 ,len(data)):
    data[i] = word_tokenize(data[i])
    data[i] = ([word for word in data[i] if word  not in stop])
    data[i] = ([word for word in data[i] if word  not in stp])
    
    data[i] =' '.join(str(data[i]).split(' '))
    
    corpus.append(data[i])
dfres = pd.DataFrame({'text': data, 'value': valueto})
print(data[:200])


["['आये', 'दीदी', 'पटेलबोस', 'भगत', 'सिंह', 'राज', 'गुरु', 'सुखदेव', 'सब', 'याद', 'गए।', 'नेहरू', 'महान', 'था।']", "['मादरचोद']", "['आस्था', 'महापर्व', 'छठी', 'माँ', 'बच्चों', 'निर्जला', 'व्रत', 'बच्चा', 'पलायन', 'मार', 'झेल', 'माँ', 'बेटे', 'निक्कमी', 'समझ']", "['वर्ष', 'भारत', 'अक्टूबर', 'प्रतिवर्ष', 'राष्ट्रीय', 'एकता', 'दिवस', 'रूप', 'मनाने', 'निर्णय', 'अक्टूबर', 'दिन', 'दिन', 'भारत', 'माता', 'लौह', 'पुरुष', 'सरदार', 'पटेल', 'हीरा']", "['फ्री', 'टिकट', 'ढिंढोरा', 'पीट', 'सच', 'जानिए', 'जुड़िए', 'लाइव।']", "['घर', 'रुपए', 'दीया', 'जलाया', 'कीमत', 'मुश्किल', 'बाती', 'तेल', 'अधिकतम', 'होगी।', 'मान', 'दीया', 'प्रज्वलित', 'कर्मचारी', 'दीया', 'लगाया', 'कीमत', 'रू', 'हैं।', 'यूपी', 'दीया', 'लगभग', 'लिया।']", "['बीजेपी', 'शिवसेना', 'गांड', 'लात', 'मारने']", "['साल', 'प्रदेश', 'जनता', 'विश्वास', 'जीता', 'विकास', 'नाम', 'विश्वास', 'नतीजा', 'गरीबी', 'प्रदेश', 'विकास', 'सिर्फ', 'विश्वासघात।', 'कमियां', 'गिना', 'है।']", "['गांड़', 'डंडा', 'डालने', 'कमजोर']", "['टोटी', 'चोर']", "['पूर्वांचल', 'ब

In [111]:

corpus

["['आये', 'दीदी', 'पटेलबोस', 'भगत', 'सिंह', 'राज', 'गुरु', 'सुखदेव', 'सब', 'याद', 'गए।', 'नेहरू', 'महान', 'था।']",
 "['मादरचोद']",
 "['आस्था', 'महापर्व', 'छठी', 'माँ', 'बच्चों', 'निर्जला', 'व्रत', 'बच्चा', 'पलायन', 'मार', 'झेल', 'माँ', 'बेटे', 'निक्कमी', 'समझ']",
 "['वर्ष', 'भारत', 'अक्टूबर', 'प्रतिवर्ष', 'राष्ट्रीय', 'एकता', 'दिवस', 'रूप', 'मनाने', 'निर्णय', 'अक्टूबर', 'दिन', 'दिन', 'भारत', 'माता', 'लौह', 'पुरुष', 'सरदार', 'पटेल', 'हीरा']",
 "['फ्री', 'टिकट', 'ढिंढोरा', 'पीट', 'सच', 'जानिए', 'जुड़िए', 'लाइव।']",
 "['घर', 'रुपए', 'दीया', 'जलाया', 'कीमत', 'मुश्किल', 'बाती', 'तेल', 'अधिकतम', 'होगी।', 'मान', 'दीया', 'प्रज्वलित', 'कर्मचारी', 'दीया', 'लगाया', 'कीमत', 'रू', 'हैं।', 'यूपी', 'दीया', 'लगभग', 'लिया।']",
 "['बीजेपी', 'शिवसेना', 'गांड', 'लात', 'मारने']",
 "['साल', 'प्रदेश', 'जनता', 'विश्वास', 'जीता', 'विकास', 'नाम', 'विश्वास', 'नतीजा', 'गरीबी', 'प्रदेश', 'विकास', 'सिर्फ', 'विश्वासघात।', 'कमियां', 'गिना', 'है।']",
 "['गांड़', 'डंडा', 'डालने', 'कमजोर']",
 "['टोटी', 'चोर']",
 "['पूर्

In [112]:
dfres.head()

text  value
0  ['आये', 'दीदी', 'पटेलबोस', 'भगत', 'सिंह', 'राज...    0.0
1                                        ['मादरचोद']    1.0
2  ['आस्था', 'महापर्व', 'छठी', 'माँ', 'बच्चों', '...    0.0
3  ['वर्ष', 'भारत', 'अक्टूबर', 'प्रतिवर्ष', 'राष्...    0.0
4  ['फ्री', 'टिकट', 'ढिंढोरा', 'पीट', 'सच', 'जानि...    0.0

In [113]:
#bow model
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report
from sklearn.pipeline import Pipeline

In [114]:
import regex 

def custom_analyzer(text):
    words = regex.findall(r'\w{2,}', text) # extract words of at least 2 letters since hindi words were getting stemmed
    for w in words:
        yield w


cv = CountVectorizer(analyzer = custom_analyzer )
X = cv.fit_transform(corpus).toarray()
print(X.shape)

(855, 4039)


In [115]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [116]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [117]:
print(cv.vocabulary_)

{'आये': 1952, 'दीदी': 2727, 'पटेलबोस': 2885, 'भगत': 3245, 'सिंह': 3852, 'राज': 3531, 'गुरु': 2330, 'सुखदेव': 3872, 'सब': 3796, 'याद': 3476, 'गए': 2288, 'नेहरू': 2863, 'महान': 3354, 'था': 2674, 'मादरचोद': 3371, 'आस्था': 1962, 'महापर्व': 3355, 'छठी': 2442, 'माँ': 3363, 'बच्चों': 3105, 'निर्जला': 2844, 'व्रत': 3721, 'बच्चा': 3102, 'पलायन': 2913, 'मार': 3386, 'झेल': 2568, 'बेटे': 3211, 'निक्कमी': 2833, 'समझ': 3801, 'वर्ष': 3669, 'भारत': 3275, 'अक्टूबर': 1828, 'प्रतिवर्ष': 3015, 'राष्ट्रीय': 3551, 'एकता': 2037, 'दिवस': 2723, 'रूप': 3565, 'मनाने': 3330, 'निर्णय': 2845, 'दिन': 2715, 'माता': 3368, 'लौह': 3661, 'पुरुष': 2961, 'सरदार': 3815, 'पटेल': 2884, 'हीरा': 4007, 'फ्री': 3084, 'टिकट': 2578, 'ढिंढोरा': 2622, 'पीट': 2952, 'सच': 3782, 'जानिए': 2519, 'जुड़िए': 2543, 'लाइव': 3609, 'घर': 2343, 'रुपए': 3561, 'दीया': 2730, 'जलाया': 2490, 'कीमत': 2186, 'मुश्किल': 3432, 'बाती': 3172, 'तेल': 2664, 'अधिकतम': 1845, 'होगी': 4033, 'मान': 3374, 'प्रज्वलित': 3011, 'कर्मचारी': 2117, 'लगाया': 3595, 'रू': 356

In [118]:
y=pd.get_dummies(dfres['value'])
y=y.iloc[:,1].values
print(y)
y.shape


[0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 0 0 0 1 0 1 1
 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 0 1
 0 0 0 1 0 1 1 0 1 0 1 1 0 1 1 1 0 1 1 1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1
 0 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 1 1 1 0
 1 0 1 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0
 1 0 0 0 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1
 1 1 1 0 0 1 0 1 1 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0 0 0 1
 0 1 0 0 0 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 0 0 0 0 0 1 1 1 1 

(855,)

In [119]:
#multinomial naive bayes in bow
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 0)
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)

ac_mnb = accuracy_score(y_pred, y_test)
print('accuracy %s' % ac_mnb)


confusion_matrix(y_test , y_pred)


accuracy 0.8249027237354085


array([[ 49,  43],
       [  2, 163]], dtype=int64)

In [120]:
#logistic regression on bow
from sklearn.linear_model import LogisticRegression
lgmodel=LogisticRegression().fit(X_train, y_train)
y_lr=lgmodel.predict(X_test)
ac=accuracy_score(y_lr , y_test)
print('accuracy %s'% ac)
confusion_matrix(y_test , y_lr)

accuracy 0.7198443579766537


array([[ 21,  71],
       [  1, 164]], dtype=int64)

In [121]:
#tfidf
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
tfv = TfidfVectorizer(analyzer = custom_analyzer)
X1 = tfv.fit_transform(corpus).toarray()
print(X1.shape)

(855, 4039)


In [122]:
print(tfv.vocabulary_)

{'आये': 1952, 'दीदी': 2727, 'पटेलबोस': 2885, 'भगत': 3245, 'सिंह': 3852, 'राज': 3531, 'गुरु': 2330, 'सुखदेव': 3872, 'सब': 3796, 'याद': 3476, 'गए': 2288, 'नेहरू': 2863, 'महान': 3354, 'था': 2674, 'मादरचोद': 3371, 'आस्था': 1962, 'महापर्व': 3355, 'छठी': 2442, 'माँ': 3363, 'बच्चों': 3105, 'निर्जला': 2844, 'व्रत': 3721, 'बच्चा': 3102, 'पलायन': 2913, 'मार': 3386, 'झेल': 2568, 'बेटे': 3211, 'निक्कमी': 2833, 'समझ': 3801, 'वर्ष': 3669, 'भारत': 3275, 'अक्टूबर': 1828, 'प्रतिवर्ष': 3015, 'राष्ट्रीय': 3551, 'एकता': 2037, 'दिवस': 2723, 'रूप': 3565, 'मनाने': 3330, 'निर्णय': 2845, 'दिन': 2715, 'माता': 3368, 'लौह': 3661, 'पुरुष': 2961, 'सरदार': 3815, 'पटेल': 2884, 'हीरा': 4007, 'फ्री': 3084, 'टिकट': 2578, 'ढिंढोरा': 2622, 'पीट': 2952, 'सच': 3782, 'जानिए': 2519, 'जुड़िए': 2543, 'लाइव': 3609, 'घर': 2343, 'रुपए': 3561, 'दीया': 2730, 'जलाया': 2490, 'कीमत': 2186, 'मुश्किल': 3432, 'बाती': 3172, 'तेल': 2664, 'अधिकतम': 1845, 'होगी': 4033, 'मान': 3374, 'प्रज्वलित': 3011, 'कर्मचारी': 2117, 'लगाया': 3595, 'रू': 356

In [123]:
X1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [124]:
X1[1][4030]

0.0

In [125]:
y1=pd.get_dummies(dfres['value'])
y1=y1.iloc[:,1].values
print(y1)
y1.shape


[0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 0 0 0 1 0 1 1
 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 0 1
 0 0 0 1 0 1 1 0 1 0 1 1 0 1 1 1 0 1 1 1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1
 0 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 1 1 1 0
 1 0 1 0 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0
 1 0 0 0 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1
 1 1 1 0 0 1 0 1 1 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 0 0 0 1
 0 1 0 0 0 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 0 0 0 0 0 1 1 1 1 

(855,)

In [126]:
#tfidf naive bayes
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.3, random_state = 0)

tfidfmodel = MultinomialNB().fit(X_train, y_train)

ypred=tfidfmodel.predict(X_test)

ac_ = accuracy_score(ypred, y_test)
print('accuracy %s' % ac_)


confusion_matrix(y_test , ypred)

accuracy 0.6964980544747081


array([[ 14,  78],
       [  0, 165]], dtype=int64)

In [127]:
#logistic regression on tfidf
tfidflg=LogisticRegression().fit(X_train, y_train)
y_tf=tfidflg.predict(X_test)
ac=accuracy_score(y_tf , y_test)
print('accuracy %s'% ac)
confusion_matrix(y_test , y_tf)

accuracy 0.6653696498054474


array([[  6,  86],
       [  0, 165]], dtype=int64)